[project]
name = "pytket-pennylane"
dynamic = ["version"]
requires-python = ">=3.11,<4.0"

description = "Pytket extension and Pennylane plugin."
license = { file = "LICENSE" }
readme = "README.md"
authors = [
    { name = "TKET development team", email = "tket-support@quantinuum.com" }
]
maintainers = [
    { name = "TKET development team", email = "tket-support@quantinuum.com" },
]
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "pytket >= 2.11.0",
    "pennylane >= 0.43.1",
    "pytket-qiskit >= 0.75.0",
]

[project.entry-points."pennylane.plugins"]
"pytket.pytketdevice" = "pytket.extensions.pennylane:PytketDevice"

[project.urls]
documentation = "https://tket.quantinuum.com/extensions/pytket-pennylane/index.html"
source = "https://github.com/Quantinuum/pytket-pennylane"
tracker = "https://github.com/Quantinuum/pytket-pennylane/issues"

[tool.setuptools.packages]
find = {}

[tool.setuptools.dynamic]
version = {attr = "pytket.extensions.pennylane._metadata.__extension_version__"}

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.uv]
dev-dependencies = [
    "pytest >=8.3.2,<9",
    "pytest-timeout ~=2.4.0",
    "ruff >=0.6.2,<0.7",
    "mypy >=1.11.1,<2",
    "hypothesis >=6.111.1,<7",
    "pre-commit >=3.8.0,<4",
    "pyupgrade >=2.29,<4.0",
    "pytket-cirq",
    "pytest-mock",
    "flaky",
]
